export const SOCIAL_LINKS = {
  linktree: "https://shop-now",  // redirects to shop
  tiktok: "https://www.tiktok.com/@hafiznaveedchuhan",
  reddit: "https://www.reddit.com/user/Particular-Ship6288/",
  pinterest: "https://www.pinterest.com/hafiznaveedu/",
  whatsapp: "https://wa.me/923002385209?text=Hi!%20I%20found%20your%20website%20and%20I'm%20interested%20in%20your%20products!",
  email: "hafiznaveedchuhan@gmail.com",
  blog: "https://deals-hub-2026.blogspot.com",
}

export const products = [
  {
    id: 1,
    name: "LED Light Therapy Face Mask",
    shortName: "LED Face Mask",
    tagline: "7-Day Skin Transformation — Clinically Proven",
    price: "$15 – $45",
    priceNote: "1 piece | Free shipping",
    badge: "⭐ Best Seller",
    badgeColor: "rose",
    emoji: "✨",
    category: "Skincare & Beauty",
    rating: 4.9,
    reviews: 2847,
    soldCount: "5000+ sold",
    affiliateLink: "https://s.click.aliexpress.com/e/_c2uKjCjp",
    affiliateId: "aliexpress",
    productId: "led-face-mask",
    features: [
      "7 color LED light therapy modes",
      "Red 630nm — anti-aging & collagen boost",
      "Blue 415nm — kills acne bacteria",
      "Green 560nm — pigmentation reduction",
      "Near infrared — deep tissue healing",
      "Wireless rechargeable USB-C",
      "Results visible in 7 days",
      "Certified: UKCA | CE | ISO"
    ],
    benefits: [
      "Replaces $300+ salon facials",
      "Dermatologist-approved technology",
      "FDA-cleared light wavelengths",
      "One-size fits all design"
    ],
    targetAudience: "Women 22–45 | Skincare enthusiasts | UK/USA/Canada",
    images: [
      "/images/MASK-1.jpg",
      "/images/MASK-2.jpg",
      "/images/MASK-3.jpg",
      "/images/MASK-4.jpg",
      "/images/MASK-5.jpg",
    ],
    fallback: "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600&q=80",
    accent: "#f43f5e",
    accentLight: "#fff1f2",
    description: "Professional-grade LED light therapy mask delivering salon-quality results at home. 7-color spectrum targets every skin concern — from fine lines to acne — in just 7 days of daily use."
  },
  {
    id: 2,
    name: "Smart Posture Corrector",
    shortName: "Posture Corrector",
    tagline: "Fixes Back Pain in 2 Weeks — WFH Essential",
    price: "$5 – $20",
    priceNote: "1 piece | Multiple variants",
    badge: "💜 Top Rated",
    badgeColor: "violet",
    emoji: "🧘",
    category: "Health & Wellness",
    rating: 4.8,
    reviews: 3241,
    soldCount: "1000+ sold",
    affiliateLink: "https://s.click.aliexpress.com/e/_c3MmvTa7",
    affiliateId: "aliexpress",
    productId: "posture-corrector",
    features: [
      "Smart vibration alert when slouching",
      "Ultra-lightweight — only 85g",
      "Breathable mesh fabric",
      "Invisible under clothing",
      "USB-C rechargeable — 30hr battery",
      "Adjustable straps — fits all sizes",
      "No app required — plug & play",
      "Results guaranteed in 14 days"
    ],
    benefits: [
      "Saves £80+ physio session fees",
      "Relieves neck & back pain",
      "Improves confidence & posture",
      "Approved by physiotherapists"
    ],
    targetAudience: "Office workers | WFH | Remote workers | UK/USA/Canada",
    images: [
      "/images/POSTURE-1.png",
      "/images/POSTURE-2.png",
      "/images/POSTURE-3.jpg",
      "/images/POSTURE-4.jpg",
      "/images/POSTURE-5.jpg",
      "/images/POSTURE-6.jpg",
    ],
    fallback: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    accent: "#8b5cf6",
    accentLight: "#f5f3ff",
    description: "The only posture corrector with intelligent vibration feedback. Trusted by 40M+ desk workers worldwide. Wear it 30 minutes daily and feel the difference within 2 weeks."
  },
  {
    id: 3,
    name: "Professional Massage Gun",
    shortName: "Massage Gun",
    tagline: "Same as $400 Theragun — For Only $40",
    price: "$20 – $60",
    priceNote: "1 piece | 6 attachments included",
    badge: "🔥 Best Value",
    badgeColor: "amber",
    emoji: "💪",
    category: "Fitness & Recovery",
    rating: 4.7,
    reviews: 1893,
    soldCount: "300+ sold",
    affiliateLink: "https://s.click.aliexpress.com/e/_c31ybjMr",
    affiliateId: "aliexpress",
    productId: "massage-gun",
    features: [
      "30 adjustable speed levels",
      "6 professional massage heads",
      "Ultra-quiet 40dB brushless motor",
      "2400–3200 RPM amplitude",
      "8-hour battery per charge",
      "Premium carrying case included",
      "Deep tissue percussion therapy",
      "Endorsed by professional athletes"
    ],
    benefits: [
      "Same tech as $400 Theragun Pro",
      "Instant post-workout recovery",
      "Eliminates DOMS muscle soreness",
      "Compact — fits in gym bag"
    ],
    targetAudience: "Gym lovers | Athletes | Fitness enthusiasts | UK/USA/Canada",
    images: [
      "/images/GUN-MASK-1.jpg",
      "/images/GUN-MASK-2.jpg",
      "/images/GUN-MASK-3.jpg",
      "/images/GUN-MASK-4.jpg",
      "/images/GUN-MASK-5.jpg",
    ],
    fallback: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80",
    accent: "#f59e0b",
    accentLight: "#fffbeb",
    description: "Professional percussion therapy trusted by personal trainers and athletes across UK, USA & Canada. 30 speed levels, 6 specialized heads, whisper-quiet motor."
  },
  {
    id: 4,
    name: "Father's Day Business Gift Set",
    shortName: "Business Gift Set",
    tagline: "Perfect Father's Day Gift — Watch, Wallet & Cologne",
    price: "$8 – $20",
    priceNote: "1 piece | Express shipping",
    badge: "🎁 Father's Day Pick",
    badgeColor: "emerald",
    emoji: "🎁",
    category: "Father's Day Gifts",
    rating: 4.6,
    reviews: 847,
    soldCount: "200+ sold",
    affiliateLink: "https://s.click.aliexpress.com/e/_c3QUrIwB",
    affiliateId: "aliexpress",
    productId: "fathers-day-gift",
    features: [
      "Premium quartz watch with leather strap",
      "Genuine leather wallet — slim design",
      "Stainless steel keychain",
      "Signature cologne / perfume",
      "Luxury gift box packaging",
      "Available in Burgundy & Black",
      "Size: 20x20x5cm gift box",
      "Reorder rate: 25% — highly trusted"
    ],
    benefits: [
      "All-in-one Father's Day solution",
      "Premium packaging — ready to gift",
      "Verified AliExpress supplier",
      "Ships direct to UK, USA & Canada"
    ],
    targetAudience: "Father's Day shoppers | Gift buyers | UK/USA/Canada",
    images: [
      "/images/GIFT-SET-1.jpg",
      "/images/GIFT-SET-2.jpg",
      "/images/GIFT-SET-3.jpg",
    ],
    fallback: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80",
    accent: "#10b981",
    accentLight: "#ecfdf5",
    description: "The ultimate Father's Day gift set featuring a premium quartz watch, genuine leather wallet, stainless steel keychain, and signature cologne — all in a luxury gift box."
  }
]

export const testimonials = [
  { name: "Sarah M.", location: "London, UK", product: "LED Face Mask", rating: 5,
    text: "After 7 days my skin looks 10 years younger. The red light therapy is incredible. Best £50 I've ever spent!", avatar: "S", verified: true },
  { name: "James T.", location: "New York, USA", product: "Posture Corrector", rating: 5,
    text: "Working from home destroyed my back. This device changed everything. Vibration alerts keep me sitting straight all day!", avatar: "J", verified: true },
  { name: "Emma K.", location: "Toronto, Canada", product: "Massage Gun", rating: 5,
    text: "Was paying $80 for physio twice a week. This massage gun does the same job at home. Life-changing!", avatar: "E", verified: true },
  { name: "David R.", location: "Manchester, UK", product: "Posture Corrector", rating: 5,
    text: "Six hours at desk daily was killing my neck. Three weeks with this and colleagues think I've been to a chiropractor!", avatar: "D", verified: true },
  { name: "Priya L.", location: "Vancouver, Canada", product: "LED Face Mask", rating: 5,
    text: "Blue light cleared my hormonal acne in 3 weeks. My dermatologist was genuinely impressed with my progress!", avatar: "P", verified: true },
  { name: "Mike W.", location: "Chicago, USA", product: "Massage Gun", rating: 4,
    text: "As a personal trainer, I now recommend this to all my clients. Rivals my $400 Theragun at a quarter of the price!", avatar: "M", verified: true },
  { name: "Robert H.", location: "Houston, USA", product: "Father's Day Gift Set", rating: 5,
    text: "Bought this for my dad for Father's Day. The packaging is stunning and quality is premium. He absolutely loved it!", avatar: "R", verified: true },
]
