export const SOCIAL_LINKS = {
  linktree: "https://shop-now",  // redirects to shop
  tiktok: "https://www.tiktok.com/@hafiznaveedchuhan",
  reddit: "https://www.reddit.com/user/Particular-Ship6288/",
  pinterest: "https://www.pinterest.com/hafiznaveedu/",
  whatsapp: "https://wa.me/923002385209?text=Hi!%20I%20found%20your%20website%20and%20I'm%20interested%20in%20your%20products!",
  email: "hafiznaveedchuhan@gmail.com",
  blog: "https://deals-hub-2026.blogspot.com",
}

export const products = [
  {
    id: 1,
    name: "LED Light Therapy Face Mask",
    shortName: "LED Face Mask",
    tagline: "7-Day Skin Transformation — Clinically Proven",
    price: "$15 – $45",
    priceNote: "1 piece | Free shipping",
    badge: "⭐ Best Seller",
    badgeColor: "rose",
    emoji: "✨",
    category: "Skincare & Beauty",
    rating: 4.9,
    reviews: 2847,
    soldCount: "5000+ sold",
    affiliateLink: "https://s.click.aliexpress.com/e/_c2uKjCjp",
    affiliateId: "aliexpress",
    productId: "led-face-mask",
    features: [
      "7 color LED light therapy modes",
      "Red 630nm — anti-aging & collagen boost",
      "Blue 415nm — kills acne bacteria",
      "Green 560nm — pigmentation reduction",
      "Near infrared — deep tissue healing",
      "Wireless rechargeable USB-C",
      "Results visible in 7 days",
      "Certified: UKCA | CE | ISO"
    ],
    benefits: [
      "Replaces $300+ salon facials",
      "Dermatologist-approved technology",
      "FDA-cleared light wavelengths",
      "One-size fits all design"
    ],
    targetAudience: "Women 22–45 | Skincare enthusiasts | UK/USA/Canada",
    images: [
      "/images/MASK-1.jpg",
      "/images/MASK-2.jpg",
      "/images/MASK-3.jpg",
      "/images/MASK-4.jpg",
      "/images/MASK-5.jpg",
    ],
    fallback: "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600&q=80",
    accent: "#f43f5e",
    accentLight: "#fff1f2",
    description: "Professional-grade LED light therapy mask delivering salon-quality results at home. 7-color spectrum targets every skin concern — from fine lines to acne — in just 7 days of daily use."
  },
  {
    id: 2,
    name: "Smart Posture Corrector",
    shortName: "Posture Corrector",
    tagline: "Fixes Back Pain in 2 Weeks — WFH Essential",
    price: "$5 – $20",
    priceNote: "1 piece | Multiple variants",
    badge: "💜 Top Rated",
    badgeColor: "violet",
    emoji: "🧘",
    category: "Health & Wellness",
    rating: 4.8,
    reviews: 3241,
    soldCount: "1000+ sold",
    affiliateLink: "https://s.click.aliexpress.com/e/_c3MmvTa7",
    affiliateId: "aliexpress",
    productId: "posture-corrector",
    features: [
      "Smart vibration alert when slouching",
      "Ultra-lightweight — only 85g",
      "Breathable mesh fabric",
      "Invisible under clothing",
      "USB-C rechargeable — 30hr battery",
      "Adjustable straps — fits all sizes",
      "No app required — plug & play",
      "Results guaranteed in 14 days"
    ],
    benefits: [
      "Saves £80+ physio session fees",
      "Relieves neck & back pain",
      "Improves confidence & posture",
      "Approved by physiotherapists"
    ],
    targetAudience: "Office workers | WFH | Remote workers | UK/USA/Canada",
    images: [
      "/images/POSTURE-1.png",
      "/images/POSTURE-2.png",
      "/images/POSTURE-3.jpg",
      "/images/POSTURE-4.jpg",
      "/images/POSTURE-5.jpg",
      "/images/POSTURE-6.jpg",
    ],
    fallback: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    accent: "#8b5cf6",
    accentLight: "#f5f3ff",
    description: "The only posture corrector with intelligent vibration feedback. Trusted by 40M+ desk workers worldwide. Wear it 30 minutes daily and feel the difference within 2 weeks."
  },
  {
    id: 3,
    name: "Professional Massage Gun",
    shortName: "Massage Gun",
    tagline: "Same as $400 Theragun — For Only $40",
    price: "$20 – $60",
    priceNote: "1 piece | 6 attachments included",
    badge: "🔥 Best Value",
    badgeColor: "amber",
    emoji: "💪",
    category: "Fitness & Recovery",
    rating: 4.7,
    reviews: 1893,
    soldCount: "300+ sold",
    affiliateLink: "https://s.click.aliexpress.com/e/_c31ybjMr",
    affiliateId: "aliexpress",
    productId: "massage-gun",
    features: [
      "30 adjustable speed levels",
      "6 professional massage heads",
      "Ultra-quiet 40dB brushless motor",
      "2400–3200 RPM amplitude",
      "8-hour battery per charge",
      "Premium carrying case included",
      "Deep tissue percussion therapy",
      "Endorsed by professional athletes"
    ],
    benefits: [
      "Same tech as $400 Theragun Pro",
      "Instant post-workout recovery",
      "Eliminates DOMS muscle soreness",
      "Compact — fits in gym bag"
    ],
    targetAudience: "Gym lovers | Athletes | Fitness enthusiasts | UK/USA/Canada",
    images: [
      "/images/GUN-MASK-1.jpg",
      "/images/GUN-MASK-2.jpg",
      "/images/GUN-MASK-3.jpg",
      "/images/GUN-MASK-4.jpg",
      "/images/GUN-MASK-5.jpg",
    ],
    fallback: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80",
    accent: "#f59e0b",
    accentLight: "#fffbeb",
    description: "Professional percussion therapy trusted by personal trainers and athletes across UK, USA & Canada. 30 speed levels, 6 specialized heads, whisper-quiet motor."
  },
  {
    id: 4,
    name: "Father's Day Business Gift Set",
    shortName: "Business Gift Set",
    tagline: "Perfect Father's Day Gift — Watch, Wallet & Cologne",
    price: "$8 – $20",
    priceNote: "1 piece | Express shipping",
    badge: "🎁 Father's Day Pick",
    badgeColor: "emerald",
    emoji: "🎁",
    category: "Father's Day Gifts",
    rating: 4.6,
    reviews: 847,
    soldCount: "200+ sold",
    affiliateLink: "https://s.click.aliexpress.com/e/_c3QUrIwB",
    affiliateId: "aliexpress",
    productId: "fathers-day-gift",
    features: [
      "Premium quartz watch with leather strap",
      "Genuine leather wallet — slim design",
      "Stainless steel keychain",
      "Signature cologne / perfume",
      "Luxury gift box packaging",
      "Available in Burgundy & Black",
      "Size: 20x20x5cm gift box",
      "Reorder rate: 25% — highly trusted"
    ],
    benefits: [
      "All-in-one Father's Day solution",
      "Premium packaging — ready to gift",
      "Verified AliExpress supplier",
      "Ships direct to UK, USA & Canada"
    ],
    targetAudience: "Father's Day shoppers | Gift buyers | UK/USA/Canada",
    images: [
      "/images/GIFT-SET-1.jpg",
      "/images/GIFT-SET-2.jpg",
      "/images/GIFT-SET-3.jpg",
    ],
    fallback: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80",
    accent: "#10b981",
    accentLight: "#ecfdf5",
    description: "The ultimate Father's Day gift set featuring a premium quartz watch, genuine leather wallet, stainless steel keychain, and signature cologne — all in a luxury gift box."
  },
  {
    id: 5,
    name: "Electric Neck & Shoulder Massager",
    shortName: "Neck Massager",
    tagline: "Neck Pain Gone in 15 Minutes — Heat + 4D Vibration",
    price: "$20 – $45",
    priceNote: "1 piece | Free shipping",
    badge: "🔥 Hot Seller",
    badgeColor: "orange",
    emoji: "💆",
    category: "Health & Wellness",
    rating: 4.6,
    reviews: 10000,
    soldCount: "10,000+ sold",
    affiliateLink: "https://s.click.aliexpress.com/e/_c4eSrdKL",
    affiliateId: "aliexpress",
    productId: "neck-massager",
    features: [
      "4D Shiatsu deep tissue kneading",
      "Heating vibration therapy",
      "Cervical traction support",
      "3 adjustable massage modes",
      "Portable & rechargeable",
      "Auto shut-off safety feature",
      "Fits all neck sizes",
      "Results in just 15 minutes daily"
    ],
    benefits: [
      "Relieves desk job neck pain instantly",
      "Replaces expensive physio sessions",
      "Perfect WFH essential",
      "Ideal Father's Day gift"
    ],
    targetAudience: "Office workers | WFH professionals | Athletes | UK/USA/Canada",
    images: [
      "/images/NECK-1.jpg",
      "/images/NECK-2.jpg",
      "/images/NECK-3.jpg",
    ],
    fallback: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80",
    accent: "#e8530a",
    accentLight: "#fff7ed",
    description: "Professional-grade electric neck massager with heat & 4D vibration therapy. Trusted by 10,000+ customers for instant relief from neck pain, shoulder tension & desk job stiffness. Ships FREE to USA, UK & Canada."
  },
  {
    id: 6,
    name: "Ice Roller & Gua Sha Face Set",
    shortName: "Ice Roller & Gua Sha",
    tagline: "Glow Skin in 7 Days — K-Beauty Secret Revealed",
    price: "$5 – $15",
    priceNote: "1-3 piece set | Free shipping",
    badge: "✨ Trending Now",
    badgeColor: "cyan",
    emoji: "🧊",
    category: "Skincare & Beauty",
    rating: 4.6,
    reviews: 3000,
    soldCount: "3,000+ sold",
    affiliateLink: "https://s.click.aliexpress.com/e/_c3PaxjYR",
    affiliateId: "aliexpress",
    productId: "ice-roller-gua-sha",
    features: [
      "Stainless steel ice roller",
      "Natural gua sha scraping tool",
      "De-puffs & tightens skin",
      "Reduces fine lines & wrinkles",
      "Minimizes pores naturally",
      "Boosts blood circulation",
      "Dermatologist recommended",
      "Works with serums & moisturizers"
    ],
    benefits: [
      "K-Beauty glass skin at home",
      "Replaces $200+ facial treatments",
      "Anti-aging + acne reduction",
      "Perfect skincare gift for her"
    ],
    targetAudience: "Women 18–45 | Skincare lovers | K-beauty fans | UK/USA/Canada/Korea",
    images: [
      "/images/ICE-1.jpg",
      "/images/ICE-2.jpg",
      "/images/ICE-3.jpg",
    ],
    fallback: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&q=80",
    accent: "#0ea5e9",
    accentLight: "#f0f9ff",
    description: "The K-Beauty secret millions swear by! Ice Roller + Gua Sha Set de-puffs, tightens & brightens your skin naturally. 3,000+ sold worldwide. Dermatologist recommended. Ships FREE to USA, UK, Canada & Korea."
  },
  {
    id: 7,
    name: "LIGE Smart Fitness Band & Watch",
    shortName: "Smart Fitness Band",
    tagline: "Best Graduation Gift 2026 — Track Everything",
    price: "$10 – $30",
    priceNote: "1 piece | Free shipping",
    badge: "🎓 Grad Gift Pick",
    badgeColor: "purple",
    emoji: "⌚",
    category: "Tech & Fitness",
    rating: 4.1,
    reviews: 118,
    soldCount: "1,000+ sold",
    affiliateLink: "https://s.click.aliexpress.com/e/_c34f0nNp",
    affiliateId: "aliexpress",
    productId: "smart-fitness-band",
    features: [
      "Heart rate monitoring 24/7",
      "Blood oxygen SpO2 tracking",
      "ECG health monitoring",
      "188 sport activity modes",
      "20-30 day battery life",
      "IP68 waterproof design",
      "Call & message notifications",
      "Android & iOS compatible"
    ],
    benefits: [
      "Perfect graduation gift 2026",
      "Replaces $200+ fitness trackers",
      "Stylish & affordable",
      "Ships fast to USA, UK & Canada"
    ],
    targetAudience: "Graduates | Fitness lovers | Tech enthusiasts | UK/USA/Canada/Germany",
    images: [
      "/images/BAND-1.jpg",
      "/images/BAND-2.jpg",
      "/images/BAND-3.jpg",
    ],
    fallback: "https://images.unsplash.com/photo-1523475496153-3b36fe998904?w=600&q=80",
    accent: "#8b5cf6",
    accentLight: "#f5f3ff",
    description: "The ultimate graduation gift for 2026! LIGE Smart Fitness Band with heart rate, blood oxygen, ECG & 188 sport modes. 20-30 day battery life. Waterproof. Compatible with Android & iOS. Ships FREE to USA, UK & Canada."
  },
  {
    id: 8,
    name: "RGB Smart LED Strip Lights",
    shortName: "RGB LED Strip Lights",
    tagline: "Transform Your Room in Minutes — Perfect for 4th of July Red White Blue 2026",
    price: "$8 – $25",
    priceNote: "1m–15m options | Free shipping",
    badge: "🔥 Viral 2026",
    badgeColor: "purple",
    emoji: "💡",
    category: "Home & Decor",
    rating: 4.8,
    reviews: 50000,
    soldCount: "50,000+ sold",
    affiliateLink: "https://s.click.aliexpress.com/e/_c4ltQfwb",
    affiliateId: "aliexpress",
    productId: "rgb-led-strip-lights",
    features: [
      "16 million color options via app",
      "WiFi + Bluetooth smart control",
      "Works with Alexa & Google Home",
      "Music sync mode — beats with rhythm",
      "Timer & scheduling function",
      "Waterproof flexible design",
      "Easy peel & stick installation",
      "Available 1m to 15m lengths"
    ],
    benefits: [
      "Instant room aesthetic transformation",
      "Perfect bedroom & gaming setup",
      "Viral Pinterest & TikTok content",
      "Great gift for teens & students worldwide"
    ],
    targetAudience: "Gen Z & Millennials | Gamers | Students | USA, UK, Canada, Germany & All Over the World",
    images: [
      "/images/LED-STRIP-1.jpg",
      "/images/LED-STRIP-2.jpg",
      "/images/LED-STRIP-3.jpg",
      "/images/LED-STRIP-4.jpg",
    ],
    fallback: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    accent: "#7c3aed",
    accentLight: "#f5f3ff",
    description: "Transform any room instantly with Smart RGB LED Strip Lights! 16 million colors, WiFi control, music sync & works with Alexa. Perfect for 4th of July 2026 — set Red White Blue mode for USA Independence Day celebrations! The #1 viral room aesthetic product of 2026. 50,000+ sold. Ships FREE to USA, UK, Canada, Germany & All Over the World!"
  },
  {
    id: 9,
    name: "Bluetooth Smart Aroma Diffuser",
    shortName: "Aroma Diffuser",
    tagline: "Hotel-Quality Scent at Home — Summer & 4th of July Party 2026",
    price: "$15 – $45",
    priceNote: "1 piece | Free shipping",
    badge: "✨ Pinterest Trend",
    badgeColor: "pink",
    emoji: "🌸",
    category: "Wellness & Self Care",
    rating: 4.9,
    reviews: 8000,
    soldCount: "8,000+ sold",
    affiliateLink: "https://s.click.aliexpress.com/e/_c3V22X8r",
    affiliateId: "aliexpress",
    productId: "aroma-diffuser",
    features: [
      "Bluetooth smart app control",
      "Ultra-quiet mist technology",
      "7 LED color mood lighting",
      "Auto shut-off safety feature",
      "300ml large water capacity",
      "8-10 hours continuous mist",
      "Works with all essential oils",
      "Hotel-grade scent diffusion"
    ],
    benefits: [
      "Pinterest Predicts 2026 Scent Stacking trend",
      "Reduces stress and promotes sleep",
      "Creates luxury spa atmosphere at home",
      "Perfect wellness gift worldwide"
    ],
    targetAudience: "Women 25-45 | Wellness lovers | Self-care enthusiasts | USA, UK, Canada, France & All Over the World",
    images: [
      "/images/AROMA-1.jpg",
      "/images/AROMA-2.jpg",
      "/images/AROMA-3.jpg",
      "/images/AROMA-4.jpg",
    ],
    fallback: "https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=600&q=80",
    accent: "#ec4899",
    accentLight: "#fdf2f8",
    description: "Bring the luxury spa home! Bluetooth Smart Aroma Diffuser with 7 color LED lighting & ultra-quiet mist. Pinterest Predicts 2026 Scent Stacking trend confirmed. 11% commission! Ships FREE to USA, UK, Canada, France & All Over the World."
  },
  {
    id: 10,
    name: "Premium Insulated Tumbler Thermos",
    shortName: "Insulated Tumbler",
    tagline: "Stay Hydrated in Style — 4th of July BBQ Essential 2026",
    price: "$12 – $35",
    priceNote: "700ml-1000ml | Free shipping",
    badge: "💧 Summer Must-Have",
    badgeColor: "blue",
    emoji: "🥤",
    category: "Lifestyle & Fitness",
    rating: 4.7,
    reviews: 12000,
    soldCount: "12,000+ sold",
    affiliateLink: "https://s.click.aliexpress.com/e/_c4ee3J27",
    affiliateId: "aliexpress",
    productId: "insulated-tumbler",
    features: [
      "316 stainless steel food-grade",
      "Push-suction tea separation filter",
      "Keeps cold 24hrs, hot 12hrs",
      "700ml to 1000ml capacity options",
      "Leak-proof push-button lid",
      "Fits standard car cup holders",
      "BPA-free safe materials",
      "Sleek minimalist aesthetic design"
    ],
    benefits: [
      "Summer hydration essential 2026",
      "Aesthetic Pinterest-worthy design",
      "Perfect gym, office & outdoor use",
      "Premium gift for him & her worldwide"
    ],
    targetAudience: "Fitness lovers | Office workers | Outdoor enthusiasts | USA, UK, Canada, Australia & All Over the World",
    images: [
      "/images/TUMBLER-1.jpg",
      "/images/TUMBLER-2.jpg",
      "/images/TUMBLER-3.jpg",
      "/images/TUMBLER-4.jpg",
    ],
    fallback: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80",
    accent: "#0ea5e9",
    accentLight: "#f0f9ff",
    description: "Stay hydrated in style this summer! Premium 316 Stainless Steel Insulated Tumbler with tea separation filter. Keeps drinks cold 24hrs & hot 12hrs. The most aesthetic water bottle of 2026! Ships FREE to USA, UK, Canada, Australia & All Over the World."
  },
  {
    id: 11,
    name: "4K Mini Portable Projector",
    shortName: "Mini Projector",
    tagline: "Cinema at Home — 4th of July Backyard Movie Night 2026",
    price: "$35 – $80",
    priceNote: "1 piece | Free shipping",
    badge: "🎬 Summer Bestseller",
    badgeColor: "dark",
    emoji: "📽️",
    category: "Tech & Entertainment",
    rating: 4.5,
    reviews: 5000,
    soldCount: "5,000+ sold",
    affiliateLink: "https://s.click.aliexpress.com/e/_c3Cir231",
    affiliateId: "aliexpress",
    productId: "mini-projector",
    features: [
      "4K support crystal clear picture",
      "300 ANSI lumens brightness",
      "180 degree rotation projection",
      "E-focus auto correction",
      "HDMI USB AV input ports",
      "Built-in dual speakers",
      "Compatible with Netflix & YouTube",
      "Available EU US AU UK plug"
    ],
    benefits: [
      "Backyard movie nights all summer",
      "Perfect Father Day & graduation gift",
      "Replaces 500+ dollar home theater systems",
      "Works bedroom garden & outdoor worldwide"
    ],
    targetAudience: "Families | Couples | Film lovers | USA, UK, Canada, Germany & All Over the World",
    images: [
      "/images/PROJECTOR-1.jpg",
      "/images/PROJECTOR-2.jpg",
      "/images/PROJECTOR-3.jpg",
      "/images/PROJECTOR-4.jpg",
    ],
    fallback: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=600&q=80",
    accent: "#1e293b",
    accentLight: "#f8fafc",
    description: "Create the ultimate cinema experience anywhere! 4K Mini Portable Projector with 300 ANSI lumens, auto E-focus & 180 rotation. Perfect for backyard movie nights & bedroom setup. The #1 summer tech gift of 2026! Ships FREE to USA, UK, Canada, Germany & All Over the World."
  },
  {
    id: 12,
    name: "18K Gold Chunky Chain Jewelry Set",
    shortName: "Gold Jewelry Set",
    tagline: "Glamoratti 2026 — Bold Gold for 4th of July & Summer Events",
    price: "$8 – $28",
    priceNote: "2-3 piece set | Free shipping",
    badge: "💛 Pinterest Predicts 2026",
    badgeColor: "gold",
    emoji: "✨",
    category: "Fashion & Jewelry",
    rating: 4.6,
    reviews: 20000,
    soldCount: "20,000+ sold",
    affiliateLink: "https://s.click.aliexpress.com/e/_c4EVtgd9",
    affiliateId: "aliexpress",
    productId: "gold-jewelry-set",
    features: [
      "18K gold plated stainless steel",
      "Tarnish and rust resistant",
      "Hypoallergenic safe materials",
      "Chunky chain necklace + bracelet",
      "Waterproof shower and swim safe",
      "Glamoratti inspired bold design",
      "Fits all neck and wrist sizes",
      "Comes in elegant gift packaging"
    ],
    benefits: [
      "Pinterest Predicts 2026 Glamoratti trend",
      "Perfect summer fashion statement",
      "Graduation and birthday gift idea",
      "Affordable luxury for women worldwide"
    ],
    targetAudience: "Women 18-40 | Fashion lovers | Gift seekers | USA, UK, France, Italy, Spain & All Over the World",
    images: [
      "/images/GOLD-JEWELRY-1.jpg",
      "/images/GOLD-JEWELRY-2.jpg",
      "/images/GOLD-JEWELRY-3.jpg",
      "/images/GOLD-JEWELRY-4.jpg",
    ],
    fallback: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80",
    accent: "#d97706",
    accentLight: "#fffbeb",
    description: "Make a bold statement with this 18K Gold Chunky Chain Jewelry Set! Tarnish-resistant, waterproof & hypoallergenic. Pinterest Predicts 2026 Glamoratti fashion trend confirmed. 20,000+ sold worldwide. Perfect for graduation, birthdays & summer events. Ships FREE to USA, UK, France, Italy & All Over the World!"
  },
  {
    id: 13,
    name: "4th of July RGBIC Outdoor String Lights",
    shortName: "Patriotic String Lights",
    tagline: "Light Up Your 4th of July — Red White Blue Magic 2026",
    price: "$8 – $22",
    priceNote: "5m–20m options | Free shipping",
    badge: "🇺🇸 4th July Special",
    badgeColor: "red",
    emoji: "✨",
    category: "4th of July Decor",
    rating: 4.7,
    reviews: 15000,
    soldCount: "15,000+ sold",
    affiliateLink: "https://s.click.aliexpress.com/e/_c4a2JAUF",
    affiliateId: "aliexpress",
    productId: "patriotic-string-lights-4july",
    features: [
      "RGBIC Red White Blue color modes",
      "Waterproof outdoor design IP65",
      "App + remote control included",
      "Music sync — lights beat with fireworks",
      "5m to 20m length options",
      "Easy clip installation on porch & fence",
      "Timer & schedule function",
      "Works for backyard BBQ & patio"
    ],
    benefits: [
      "Transform backyard into patriotic paradise",
      "Perfect for 4th of July BBQ party 2026",
      "USA 250th Anniversary celebration decor",
      "Ships fast — USA UK Canada All Over the World"
    ],
    targetAudience: "USA families | BBQ hosts | Patriotic decorators | All Over the World",
    images: [
      "/images/STRING-LIGHTS-1.jpg",
      "/images/STRING-LIGHTS-2.jpg",
      "/images/STRING-LIGHTS-3.jpg",
      "/images/STRING-LIGHTS-4.jpg",
    ],
    fallback: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&q=80",
    accent: "#DC2626",
    accentLight: "#FEF2F2",
    description: "Make your 4th of July 2026 unforgettable! RGBIC Outdoor String Lights in Red White Blue — perfect for backyard BBQ, porch & patio patriotic decoration. Waterproof, music sync & app controlled. America is turning 250 — celebrate in style! Ships FREE to USA & All Over the World!"
  },
  {
    id: 14,
    name: "132pcs Red White Blue Balloon Garland Kit",
    shortName: "Patriotic Balloon Set",
    tagline: "Ultimate 4th of July Party Decoration — America 250 Years 2026",
    price: "$12 – $28",
    priceNote: "132 piece set | Free shipping",
    badge: "🎉 4th July Bestseller",
    badgeColor: "blue",
    emoji: "🎈",
    category: "4th of July Decor",
    rating: 4.8,
    reviews: 20000,
    soldCount: "20,000+ sold",
    affiliateLink: "https://s.click.aliexpress.com/e/_c4PuA2PD",
    affiliateId: "aliexpress",
    productId: "patriotic-balloon-set-4july",
    features: [
      "132 pieces — red white blue balloons",
      "Star shaped foil balloons included",
      "Confetti balloons for extra sparkle",
      "Balloon garland arch kit complete",
      "Backdrop decoration included",
      "Easy DIY setup — no pump needed",
      "Indoor & outdoor use",
      "Perfect for backyard & porch decor"
    ],
    benefits: [
      "Top selling 4th of July decoration 3 years in a row",
      "Perfect USA 250th Anniversary party 2026",
      "Instagram & Pinterest worthy photos",
      "Ships fast to USA & All Over the World"
    ],
    targetAudience: "USA party hosts | BBQ families | Patriotic celebrators | All Over the World",
    images: [
      "/images/BALLOON-SET-1.jpg",
      "/images/BALLOON-SET-2.jpg",
      "/images/BALLOON-SET-3.jpg",
      "/images/BALLOON-SET-4.jpg",
    ],
    fallback: "https://images.unsplash.com/photo-1533776650769-55abe5f9d0bf?w=600&q=80",
    accent: "#1D4ED8",
    accentLight: "#EFF6FF",
    description: "The MUST-HAVE decoration for 4th of July 2026 — America turns 250! This 132-piece Red White Blue Balloon Garland Kit creates a stunning patriotic backdrop for your BBQ party. Star foil + confetti balloons included. Amazon bestseller 3 years running! Ships FREE to USA & All Over the World!"
  },
]

export const testimonials = [
  { name: "Sarah M.", location: "London, UK", product: "LED Face Mask", rating: 5,
    text: "After 7 days my skin looks 10 years younger! The red light therapy is incredible. Best £50 I have ever spent. Ships fast worldwide!", avatar: "S", verified: true },
  { name: "Priya L.", location: "Vancouver, Canada", product: "LED Face Mask", rating: 5,
    text: "Blue light cleared my hormonal acne in 3 weeks. My dermatologist was genuinely impressed. Arrived quickly from overseas!", avatar: "P", verified: true },
  { name: "James T.", location: "New York, USA", product: "Posture Corrector", rating: 5,
    text: "Working from home destroyed my back. This device changed everything. Vibration alerts keep me sitting straight all day!", avatar: "J", verified: true },
  { name: "David R.", location: "Manchester, UK", product: "Posture Corrector", rating: 5,
    text: "Six hours at desk daily was killing my neck. Three weeks with this and colleagues think I have been to a chiropractor!", avatar: "D", verified: true },
  { name: "Emma K.", location: "Toronto, Canada", product: "Massage Gun", rating: 5,
    text: "Was paying $80 for physio twice a week. This massage gun does the same job at home. Life-changing purchase!", avatar: "E", verified: true },
  { name: "Mike W.", location: "Chicago, USA", product: "Massage Gun", rating: 5,
    text: "As a personal trainer I now recommend this to all my clients. Rivals my $400 Theragun at a quarter of the price!", avatar: "M", verified: true },
  { name: "Robert H.", location: "Houston, USA", product: "Father's Day Gift Set", rating: 5,
    text: "Bought this for my dad for Father's Day. The packaging is stunning and quality is premium. He absolutely loved it!", avatar: "R", verified: true },
  { name: "Sophie B.", location: "Paris, France", product: "Father's Day Gift Set", rating: 5,
    text: "Gifted this to my husband. The watch, wallet and cologne set arrived beautifully packaged. Shipped all the way to France perfectly!", avatar: "S", verified: true },
  { name: "Anna L.", location: "Berlin, Germany", product: "Neck Massager", rating: 5,
    text: "As a software developer sitting 10 hours daily, this neck massager saved my life! Heat function is amazing. Shipped to Germany fast!", avatar: "A", verified: true },
  { name: "Chris P.", location: "Sydney, Australia", product: "Neck Massager", rating: 4,
    text: "Brilliant product for office neck pain. The 4D vibration is powerful and the heat makes it even better. Highly recommend!", avatar: "C", verified: true },
  { name: "Mia K.", location: "Seoul, South Korea", product: "Ice Roller & Gua Sha", rating: 5,
    text: "Finally found the K-Beauty secret at an amazing price! My skin looks so glowy and pores minimized in just one week!", avatar: "M", verified: true },
  { name: "Lisa F.", location: "Melbourne, Australia", product: "Ice Roller & Gua Sha", rating: 5,
    text: "De-puffs my face every morning in minutes! Arrived all the way to Australia in great condition. Absolutely worth it!", avatar: "L", verified: true },
  { name: "Jake R.", location: "Los Angeles, USA", product: "Smart Fitness Band", rating: 4,
    text: "Great graduation gift for my sister! Tracks heart rate, sleep and steps perfectly. Battery lasts over 3 weeks. Amazing value!", avatar: "J", verified: true },
  { name: "Nina T.", location: "Amsterdam, Netherlands", product: "Smart Fitness Band", rating: 5,
    text: "Ordered from Netherlands and arrived in perfect condition! Heart rate and sleep tracking are very accurate. Love the stylish design!", avatar: "N", verified: true },
  { name: "Tyler B.", location: "Austin, USA", product: "RGB LED Strip Lights", rating: 5,
    text: "Transformed my gaming room completely! The app is smooth, music sync is incredible and installation took 10 minutes. Best purchase ever!", avatar: "T", verified: true },
  { name: "Zoe H.", location: "Toronto, Canada", product: "RGB LED Strip Lights", rating: 5,
    text: "My daughter is obsessed with these! Her bedroom looks like a Pinterest dream now. Easy to set up and ships worldwide fast!", avatar: "Z", verified: true },
  { name: "Isabelle D.", location: "Lyon, France", product: "Aroma Diffuser", rating: 5,
    text: "My apartment smells like a luxury hotel now! The Bluetooth control is so convenient. Shipped to France with no issues at all!", avatar: "I", verified: true },
  { name: "Rachel G.", location: "London, UK", product: "Aroma Diffuser", rating: 5,
    text: "The 7 colour LED mood lighting is stunning! Ultra quiet mist runs all night. Perfect self-care gift for anyone worldwide!", avatar: "R", verified: true },
  { name: "Marcus J.", location: "Denver, USA", product: "Insulated Tumbler", rating: 5,
    text: "Best tumbler I have ever owned! Keeps my coffee hot for 12 hours and iced water cold all day at the gym. Gorgeous design!", avatar: "M", verified: true },
  { name: "Elena W.", location: "Madrid, Spain", product: "Insulated Tumbler", rating: 5,
    text: "Ordered from Spain and arrived quickly! The tea separation filter is genius. Premium quality at an incredible price. Ships worldwide!", avatar: "E", verified: true },
  { name: "Brian O.", location: "Dublin, Ireland", product: "Mini Projector", rating: 5,
    text: "Our backyard movie nights this summer have been EPIC! 4K picture quality is stunning. Perfect Father's Day gift. Ships internationally!", avatar: "B", verified: true },
  { name: "Sandra K.", location: "Munich, Germany", product: "Mini Projector", rating: 4,
    text: "Great quality projector for the price! Set up our bedroom cinema in minutes. Shipped to Germany perfectly packaged. Highly recommend!", avatar: "S", verified: true },
  { name: "Chloe M.", location: "Milan, Italy", product: "Gold Jewelry Set", rating: 5,
    text: "The chunky gold chain is exactly what I wanted for summer! Waterproof and tarnish-resistant. Shipped from overseas beautifully packaged!", avatar: "C", verified: true },
  { name: "Ashley R.", location: "New York, USA", product: "Gold Jewelry Set", rating: 5,
    text: "Pinterest Glamoratti trend is real and this jewelry delivers! Wore it to 3 graduation parties and received SO many compliments!", avatar: "A", verified: true },
  { name: "Ashley M.", location: "Dallas, USA", product: "Patriotic String Lights", rating: 5,
    text: "These lights made our 4th of July backyard look AMAZING! Red white blue colors synced with music during fireworks. Everyone loved it! Ships worldwide super fast!", avatar: "A", verified: true },
  { name: "Kevin R.", location: "Chicago, USA", product: "Patriotic String Lights", rating: 5,
    text: "Perfect for America's 250th birthday celebration! Waterproof worked great in our backyard. App control is so easy. Will use every July 4th from now on!", avatar: "K", verified: true },
  { name: "Jessica L.", location: "Houston, USA", product: "Patriotic Balloon Set", rating: 5,
    text: "Our 4th of July BBQ looked like a Pinterest dream! 132 balloons set up in 20 minutes. The star foil balloons are gorgeous. Fast shipping worldwide!", avatar: "J", verified: true },
  { name: "Brandon T.", location: "Phoenix, USA", product: "Patriotic Balloon Set", rating: 5,
    text: "Best 4th of July decoration I have ever bought! Red white blue balloon arch was the hit of the party. Perfect for America 250th anniversary. Highly recommend!", avatar: "B", verified: true },
]

